dist: bionic
addons:
  apt:
    update: true
    packages:
    - libbind-dev
    - libssl-dev
    - libbz2-dev
    - libidn2-dev
    - zlib1g-dev
    - libpcap-dev
    - libpcre3-dev
language: cpp
compiler:
  - gcc
install: ./autogen.sh
script:
  - ./configure --enable-warn-all
  - make dist
  - tar zxvf *.tar.gz
  - cd dnsmeter-*[0-9]
  - mkdir build
  - cd build
  - ../configure --enable-warn-all
  - make
  - src/dnsmeter -h
